// <auto-generated />
namespace Channelizer2Cloud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class channelizerdb2version4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(channelizerdb2version4));
        
        string IMigrationMetadata.Id
        {
            get { return "202109050733277_channelizerdb2version4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
